export const RANKINGS_LIST_GLOBAL = "RANKINGS_LIST_GLOBAL";
export const RANKINGS_LIST_FRIENDS = "RANKINGS_LIST_FRIENDS";
export const RANKINGS_LIST_LOCAL = "RANKINGS_LIST_LOCAL";
export const RANKINGS_SUMMARY = "RANKINGS_SUMMARY";